### ISSUE TITLE
Images here vs. Images in snyk/snyk-cli

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [snyk/snyk-images#5]
Hello,
A question, more than an issue:

What is the difference between the images here vs. those in snyk/snyk-cli? And which ones should we use to scan our dependencies?

Thanks!

**Comment by garethr** [comment]
Hi @AbdulRahmanAlHamali. Thanks for your question. As noted at the top of the README, these images are currently experimental. They aim to fix some of the limitations of the `snyk-cli` images, and to make it much easier to expand on the supported languages and frameworks. At the moment though the `snyk-cli` images are still the _official_ ones.

If the `snyk-cli` images work for you then you shouldn't see much of a difference. Both sets of images package the same Snyk CLI.

However, you might run into some challenges with the original image set:

* You might need a language or framework that's not supported (for instance Go or .NET)
* You might be using a package manager that needs some bootstrapping before being able to run Snyk (for instance Maven or Pip)
* You might be building your own images and just want a quick way of getting the Snyk executable
* They have quite specific filesystem requirements, which can make integration with other platforms tricky

In these cases the new images should help solve your problem.

Please do try these out and provide feedback. They are in active use by a number of Snyk users, and power the GitHub Actions for Snyk for instance. They are stable and automatically updated at least each week with the latest version of Snyk. 

Any other questions let me know.

**Comment by AbdulRahmanAlHamali** [comment]
Thank you for the response Gareth!

I'm going to try those out for Golang then. And will keep in mind that they are experimental
