### ISSUE TITLE
Git does not run as it's blocked by `safe.directory`, causing `go list` to fail

### ISSUE THREAD

**Issue by Frederick888** [snyk/snyk-images#57]
Starting from a recent version of Snyk image, it upgraded to Git
`2.30.2-1+deb11u1`, which backported the `safe.directory` option [1].

```sh
# image built 2 days ago
$ docker run --rm --entrypoint bash -i b44a997189b5 -c 'dpkg -l | grep -w git; git help --config | grep safe.directory'
ii  git                        1:2.30.2-1+deb11u1             amd64        fast, scalable, distributed revision control system
ii  git-man                    1:2.30.2-1+deb11u1             all          fast, scalable, distributed revision control system (manual pages)
safe.directory

# image built 9 days ago
$ docker run --rm --entrypoint bash -i 5f988dd42068 -c 'dpkg -l | grep -w git; git help --config | grep safe.directory'
ii  git                        1:2.30.2-1                     amd64        fast, scalable, distributed revision control system
ii  git-man                    1:2.30.2-1                     all          fast, scalable, distributed revision control system (manual pages)
```

Now since I guess inside Docker we run everything as root, however the
mounted Git repository is owned by user/group `runner` (uid 1000, gid
1000 IIRC), Git now refuses to do anything in the repository.

And in Go projects, apparently `snyk` calls `go list` to check the dependencies,
which calls Git internally, it now complains

```
'go list -json -deps ./...' command failed with error: error obtaining VCS status: exit status 128
    Use -buildvcs=false to disable VCS stamping.
```

Two workarounds right now. One, add a `GOFLAGS: "-buildvcs=false"` environment
variable; two, run this before Synk:

```yaml
- name: Set work directory as Git safe directory in Docker
  run: |
    git config --global safe.directory '*'
    mkdir -p /home/runner/runner/agent/_work/_temp/_github_home
    cp "$HOME/.gitconfig" "/home/runner/runner/agent/_work/_temp/_github_home/.gitconfig"
```

But I think in the long run we should either add the `safe.directory`
automatically (but don't use `*`), or run `synk` with the same uid/gid of the
owner/group of the repository.

[1] https://release.debian.org/proposed-updates/bullseye_diffs/git_2.30.2-1+deb11u1.debdiff

**Comment by bastiandoetsch** [comment]
Hey, thanks for the help. We have fixed the issue with #63. Right now, it is adding all directories within the container as trusted, but we'll in the next step look into the topic, whether this needs to be refined further. For now, we've re-established the old git behaviour to not interfere.
