### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by yeyeto2788** [snyk/snyk-images#68]
Hey guys! Is there a way to create also linux/arm64v8 images? I'm currently using Mac and I cannot make it work or at least I haven't found the way to do it.

I only see AMD64 image in DockerHub.

Cheers.

**Comment by bastiandoetsch** [comment]
Hi @yeyeto2788 , have you tried the docker `--platform` flag for running the image? (see https://stackoverflow.com/questions/67458621/how-to-run-amd64-docker-images-on-arm64-host-platform)

**Comment by yeyeto2788** [comment]
Hey @bastiandoetsch!

I did and seemed like there is only AMD64 available but I did worked around it by enabling experimenta feature in docker desktop for using rosetta (emulating amd64).

Thanks!

**Comment by cb-sl** [comment]
No plans to introduce these images.
