### ISSUE TITLE
Skip test phase for Maven

### ISSUE THREAD

**Issue by bmvermeer** [snyk/snyk-images#8]
Snyk needs to `mvn install` before running the test.
Looking at the maven lifecycle install is the after test phase.
This mean all tests will be called during a `mvn install`.
If one of the tests fails the build breaks and `snyk test` will not be reached.

I don't believe running the test suite is part of the scope.
Maybe call `mvn install -DskipTests` or make it configurable?

**Comment by garethr** [comment]
Good suggestion. If you want to submit a PR I can merge?

You can override this using `COMMAND` as described in https://github.com/snyk/snyk-images#running-bootstrap-commands, but skipping tests is a better default.

**Comment by bmvermeer** [comment]
Will do, I found out when I was using the github action you created. Great work btw.
I will post a PR shortly

**Comment by garethr** [comment]
Fixed in #9
